services:
  postgres:
    image: postgres:15-alpine
    hostname: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: money_bucket
    ports:
      - "5432:5432"
  moneybucket:
    image: money-bucket-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=DUMMY
      - AWS_SECRET_ACCESS_KEY=DUMMY
      - CONTAINER_PORT=8080
      - DB_ENDPOINT=jdbc:postgresql://postgres:5432/money_bucket
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres