openapi: "3.0.0"
info:
  version: 1.0.0
  title: Money Bucket API
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /finance-institutions:
    get:
#      summary: List all finance institutions
#      operationId: listFinanceInstitutions
      tags:
        - Finance Institutions
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        '200':
          description: A paged array of finance institutions
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinanceInstitutions"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
#      summary: Create a finance institution
#      operationId: createFinanceInstitution
      tags:
        - Finance Institutions
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /finance-institutions/{financeInstitutionId}:
    get:
      summary: Info for a specific finance institution
      operationId: getFinanceInstitutionById
      tags:
        - Finance Institutions
      parameters:
        - name: financeInstitutionId
          in: path
          required: true
          description: The id of the finance institution to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FinanceInstitution"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    FinanceInstitution:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: UUID
        name:
          type: string
    FinanceInstitutions:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/FinanceInstitution"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string