spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:tc:postgresql:15-alpine://127.0.0.1:5432/money_bucket
    username: postgres
    password: postgres
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
  test:
    database:
      replace: none