spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_ENDPOINT:jdbc:postgresql://127.0.0.1:5432/money_bucket}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: 'CREATE SCHEMA IF NOT EXISTS liquibase;'
  liquibase:
    change-log: db.changelog/db.changelog-master.xml
    liquibase-schema: liquibase
    enabled: true
server:
  port: ${CONTAINER_PORT:8080}